<?php

class AdminProductsController extends AdminProductsControllerCore
{
    public function postProcess()
    {
        // Catch the value from post param here and save it on product

        if ($_POST['submitAddCustomField']) {
            $product = new Product($_GET['id_product']);
            $product->short_desc = $_POST['short_desc'];



            $toto = $product->save();
        }


        parent::postProcess(); // TODO: Change the autogenerated stub
    }
}
